### PR TITLE
 Markup and JSX, Connecting to api

### PR DESCRIPTION
**Pull request by maryafzali24**

### CODE REVIEW

**Comment by ImaliaNsk** [comment]
Great job with your diploma project! Some issues will be necessary to correct, but on the whole it looks pretty good!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* https://prnt.sc/0jWXMmlpd_Ed Check styles for a new card: it shouldn't have a border, and also `card__publisher` element should be all uppercase and pushed down to the card bottom.
* "Show more" button appearance doesn't match the design: color, border
* Please check text styles in section `about`, both for the title and text paragraphs
* Check hover effect on a trash can: https://prnt.sc/nLETd3RghqzW
* https://prnt.sc/cgrpgSHRMQ5u Card style on mobile screens need correcting: elements shouldn't get outside of teh container, font-size of the text doesn't match the design.
* Popup layout on mobile screens doesn't match the design.
* "Search result" title has incorrect font-size on mobile screens.

- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* The layout is not responsive: https://prnt.sc/n3vev2CY-_WV Content should adapt to different screen resolutions, not have fixed width.

- [ ]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* "Nothing found" block can't be displayed.
* Links should open in new tabs

- [x]  Classes are named according to BEM specifications.
- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.

* header should be a `<header>`, not div.
* Links in `header` and `footer` should be in nav, ul or ul inside nav.

- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.

* Button "Search" is missing "active" and "hover" states

- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

## Number of points: 54

**Comment by ImaliaNsk** [comment]
Good job! You have fixed many bugs, but there are still some to work on. First of all, please note the compilation error: https://prnt.sc/gN-DOUlhZ7fl It's necessary to check the name of the file and the path you use.

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* Please check styles for the title in section `about`
* Log out button appearance doesn't match the design on mobile screens: https://prnt.sc/dQOuYF_sDAlf
* "Search" button in its default state doesn't match the design: https://prnt.sc/geD6Ojm1Wlsc

- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* The layout is not responsive: https://prnt.sc/n3vev2CY-_WV Content should adapt to different screen resolutions, not have fixed width.

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* Navigation on mobile screens doesn't work properly: burger menu doesn't open on saved-news page
* "Nothing found" block can't be displayed.
* Links in footer should open in new tabs

- [x]  Classes are named according to BEM specifications.
- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.

* Links in `header` should be in nav, ul or ul inside nav.

- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.

* https://prnt.sc/gN-DOUlhZ7fl

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.

* Button "Search" is missing "active" state

- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

## Number of points: 50

**Comment by maryafzali24** [comment]
I have updated the Trash icon file path. Is there something else I'm still missing?

**Comment by ImaliaNsk** [comment]
> I have updated the Trash icon file path. Is there something else I'm still missing?

Yes, it's also necessary to make other corrections, according to the list in the previous comment. I'll duplicate it below:

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* Please check styles for the title in section `about`
* Log out button appearance doesn't match the design on mobile screens: https://prnt.sc/dQOuYF_sDAlf
* "Search" button in its default state doesn't match the design: https://prnt.sc/geD6Ojm1Wlsc

- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* The layout is not responsive: https://prnt.sc/n3vev2CY-_WV Content should adapt to different screen resolutions, not have fixed width.

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* Navigation on mobile screens doesn't work properly: burger menu doesn't open on saved-news page
* "Nothing found" block can't be displayed.
* Links in footer should open in new tabs

- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.

* Links in `header` should be in nav, ul or ul inside nav.

- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.

* Button "Search" is missing "active" state

- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

## Number of points: 54

**Comment by maryafzali24** [comment]
I try to don't  miss any single error this time.

**Comment by ImaliaNsk** [comment]
Thanks for the fixes! The project looks better, but still needs some more corrections. Please find comments in the list below.

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* Please check styles for the title in section `about`
* "Noting found" styles don't match the design https://prnt.sc/N5P1vD4EHm6x

- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* The layout is not responsive: https://prnt.sc/n3vev2CY-_WV Content should adapt to different screen resolutions, not have fixed width.

- [ ]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* Links in footer should open in new tabs

- [x]  Classes are named according to BEM specifications.
- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.

* Links in `header` should be in nav, ul or ul inside nav.

- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

## Number of points: 56

**Comment by ImaliaNsk** [comment]
Great job, only a few points short! The project looks awesome, and just needs some polishing.

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* Image in `about` is loosing its aspect ratio: https://prnt.sc/EVrvFZrDpoiT `object-fit` will help
* "Nothing found" styles don't match the design https://prnt.sc/HaeOS7GjrqJj
* Section with Search results should be centered horizontally on big screens: https://prnt.sc/osnBbYQZJlnY
* On mobile screens, the search input and button are not aligned: https://prnt.sc/MbjCG_tFLmIN

- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* https://prnt.sc/AMUABgPIc6TJ Menu in header is broken, please check alignment of elements
* Cards should be centered on intermediate screens: https://prnt.sc/TNjbwEB-4IvE

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 75

**Comment by ImaliaNsk** [comment]
Still some refactoring is needed, the pages started to break and scroll on media screens. Please see the comments below.

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* "Noting found" styles don't match the design https://prnt.sc/HaeOS7GjrqJj
* Section with Search results should be centered horizontally on big screens: https://prnt.sc/lN-gvY2dGPk7 It now has manually set margins in pixels.
* On mobile screens, the search input and button are not aligned: https://prnt.sc/MbjCG_tFLmIN
* Modal window isn't centered: https://prnt.sc/gCMFt3HYHUsv

- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* The Home page scrolls horizontally on 320 - 327, 511 - 548, 581 - 680 Please check the left padding of the list with cards (it has a default padding now)
* The news page scrolls horizontally on 320 - 327, 511 - 548, 581 - 680
* https://prnt.sc/1QvBTCLhF8Zj https://prnt.sc/7Q9XTdamX279 Menu in header is broken, please check alignment of elements
* Cards should be centered on intermediate screens: https://prnt.sc/RP85uYLe-xB8 You can learn more about centering things in css here: https://css-tricks.com/centering-css-complete-guide/#center-horizontally

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 75

**Comment by ImaliaNsk** [comment]
Thanks for the fixes!  The page looks better on intermediate screens, most of the scrolling has been fixed. However, the score remains the same, layout on desktop and media screens requires more work:

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* "Nothing found" styles don't match the design https://prnt.sc/qduj0040yQLB Please check fon-family, and note that the block should be centered, also note the top and bottom space.
* The search result section should have limited width on big screens: https://prnt.sc/4bMV0cYrQzTu The title shouldn't be too far from the content itself.
* A recommendation: The image in the header should be stretched to the whole width.
* Home page scrolls on 1024px and 1025px screens.

- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* Both pages scroll horizontally on 320 - 373
* Cards should be centered, the heading, on the contrary, shouldn't: https://prnt.sc/ktZ_IO0XsxaH
* https://prnt.sc/kJ7A3XSSNz1G Navigation buttons are not aligned

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 75

**Comment by ImaliaNsk** [comment]
The layout will need more corrections. Currently, there are some major mismatches to the design, and responsive issues. Please find comments below.

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* https://prnt.sc/YtN28IAJqlYU Preloader isn't displayed. Note that it doesn't need white background.
* https://prnt.sc/CSwTqyTFyEMm Text "Please enter a keyword" shouldn't appear in the search results. It can be showed inside the search form.
* The search result section should have limited width on big screens: https://prnt.sc/4bMV0cYrQzTu The title shouldn't be too far from the content. Check it on really big screens, like 2800px. The title is too far on the left side.
* Home page scrolls on 1024px and 1025px screens.

- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* Both pages scroll horizontally on 320 - 348, 496 - 557, 708 - 885
* https://prnt.sc/ZlvcPgtJ_ou7 https://prnt.sc/lD7kZ7HLDe12
* Cards should be centered, the heading, on the contrary, shouldn't: https://prnt.sc/ktZ_IO0XsxaH
* https://prnt.sc/kJ7A3XSSNz1G Navigation buttons are not aligned

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 75

**Comment by ImaliaNsk** [comment]
Congratulations, the project looks just perfect, thanks for good work! I wish you success on further stages.

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 100

**Pull request merged**
